language: node_js
node_js:
  - "4.0.0"
  - "4"
  - "6"
  - "8"
  - "9"
sudo: false
cache:
  directories:
    - node_modules
script: "npm run test-cov"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
